name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Setup Elm
        uses: JorelAli/setup-elm@v2
        with:
          elm-version: 0.19.0

      - name: Install Dependencies
        run: yarn install

      - name: Build with Parcel
        run: yarn build

      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.3
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
          TARGET_BRANCH: master
